# Generated by Django 4.1.3 on 2022-11-24 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NameLayer", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Value", models.CharField(max_length=255)),
                ("Parametr", models.CharField(max_length=255)),
                ("NormParametr", models.CharField(max_length=255)),
                ("KolSolution", models.CharField(max_length=255)),
                ("KolSolutionNorm", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ParametricGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Time_create", models.DateTimeField(auto_now_add=True)),
                ("Time_update", models.DateTimeField(auto_now=True)),
                (
                    "Layer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PG.layer",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="layer",
            name="Node",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="PG.node"
            ),
        ),
    ]
