# Generated by Django 4.1.3 on 2022-11-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PG", "0002_layer_user_node_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layer",
            name="User",
        ),
        migrations.RemoveField(
            model_name="node",
            name="User",
        ),
        migrations.RemoveField(
            model_name="parametricgraph",
            name="User",
        ),
    ]
