# Generated by Django 4.1.3 on 2022-11-24 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("PG", "0003_remove_layer_user_remove_node_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametricgraph",
            name="User",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="node",
            name="KolSolution",
            field=models.CharField(default="0", max_length=255),
        ),
        migrations.AlterField(
            model_name="node",
            name="KolSolutionNorm",
            field=models.CharField(default="1", max_length=255),
        ),
        migrations.AlterField(
            model_name="node",
            name="NormParametr",
            field=models.CharField(default="1", max_length=255),
        ),
        migrations.AlterField(
            model_name="node",
            name="Parametr",
            field=models.CharField(default="1", max_length=255),
        ),
    ]
