# Generated by Django 4.1.3 on 2022-11-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PG", "0004_parametricgraph_user_alter_node_kolsolution_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="layer",
            old_name="NameLayer",
            new_name="name",
        ),
    ]
