# Generated by Django 4.1.3 on 2022-11-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PG", "0006_rename_name_layer_namelayer_layer_user_node_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="layer",
            old_name="NameLayer",
            new_name="nameLayer",
        ),
        migrations.RenameField(
            model_name="layer",
            old_name="Node",
            new_name="node",
        ),
        migrations.RenameField(
            model_name="layer",
            old_name="User",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="node",
            old_name="KolSolution",
            new_name="kolSolution",
        ),
        migrations.RenameField(
            model_name="node",
            old_name="KolSolutionNorm",
            new_name="kolSolutionNorm",
        ),
        migrations.RenameField(
            model_name="node",
            old_name="NormParametr",
            new_name="normParametr",
        ),
        migrations.RenameField(
            model_name="node",
            old_name="Parametr",
            new_name="parametr",
        ),
        migrations.RenameField(
            model_name="node",
            old_name="User",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="node",
            old_name="Value",
            new_name="value",
        ),
        migrations.RenameField(
            model_name="parametricgraph",
            old_name="Layer",
            new_name="layer",
        ),
        migrations.RenameField(
            model_name="parametricgraph",
            old_name="Name",
            new_name="name_pg",
        ),
        migrations.RenameField(
            model_name="parametricgraph",
            old_name="Time_create",
            new_name="time_create",
        ),
        migrations.RenameField(
            model_name="parametricgraph",
            old_name="Time_update",
            new_name="time_update",
        ),
        migrations.RenameField(
            model_name="parametricgraph",
            old_name="User",
            new_name="user",
        ),
    ]
