# Generated by Django 4.1.3 on 2022-11-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PG", "0007_rename_namelayer_layer_namelayer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="layer",
            old_name="nameLayer",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="node",
            old_name="value",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="parametricgraph",
            old_name="name_pg",
            new_name="name",
        ),
    ]
