# Generated by Django 4.1.3 on 2022-11-24 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PG", "0008_rename_namelayer_layer_name_rename_value_node_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layer",
            name="node",
        ),
        migrations.RemoveField(
            model_name="parametricgraph",
            name="layer",
        ),
        migrations.AddField(
            model_name="layer",
            name="pg",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="PG.parametricgraph",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="layer",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="PG.layer"
            ),
        ),
    ]
