# Generated by Django 4.1.3 on 2022-11-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PG", "0010_rename_name_parametricgraph_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="node",
            old_name="name",
            new_name="name_node",
        ),
    ]
